In [8]:
import pandas as pd
import numpy as np

df=pd.read_excel("../data/cleandata.xlsx")
df.head()
#Did I load the dataset correc

,date,Power Consumption,Outdoor Temperature,Occupancy
0,2018-05-22 00:00:00,71.98,15.72,1
1,2018-05-22 00:15:00,71.00,15.37,1
2,2018-05-22 00:30:00,65.20,15.27,0
3,2018-05-22 00:45:00,95.90,16.03,0
4,2018-05-22 01:00:00,43.60,15.28,0


In [9]:
actions = {

    0: "Do Nothing",

    1: "Reduce HVAC",

    2: "Check Equipment",

    3: "Reduce Lighting"

}

actions

{0: 'Do Nothing', 1: 'Reduce HVAC', 2: 'Check Equipment', 3: 'Reduce Lighting'}

In [10]:
action_space = list(actions.keys())

print(action_space)

[0, 1, 2, 3]


In [11]:
num_actions = len(action_space)

print("Number of Actions:", num_actions)

Number of Actions: 4


In [12]:
action_id = 1

print(
    "Selected Action:",
    actions[action_id]
)

Selected Action: Reduce HVAC


In [13]:
import random

random_action = random.choice(action_space)

print(
    "Random Action:",
    actions[random_action]
)

Random Action: Check Equipment


In [14]:
action_df = pd.DataFrame({

    "Action_ID": actions.keys(),

    "Action_Name": actions.values()

})

action_df

,Action_ID,Action_Name
0,0,Do Nothing
1,1,Reduce HVAC
2,2,Check Equipment
3,3,Reduce Lighting


In [ ]:
def get_next_state( #Environment model
    state,
    action
):

    power, occupancy, temperature = state

    if action == 0:

        # Do Nothing

        power = power

        temperature = temperature

    elif action == 1:

        # Reduce HVAC

        power = max(
            0.1,
            power - 0.3
        )

        temperature = min(
            1.0,
            temperature + 0.1
        )

    elif action == 2:

        # Check Equipment

        power = max(
            0.1,
            power - 0.1
        )

        temperature = temperature

    elif action == 3:

        # Reduce Lighting

        power = max(
            0.1,
            power - 0.2
        )

        temperature = min(
            1.0,
            temperature + 0.05
        )

    return (
        round(power, 1),
        occupancy,
        round(temperature, 1)
    )

In [18]:
def calculate_reward(
    state,
    next_state
):

    power_before = state[0]

    occupancy = state[1]

    temperature_before = state[2]

    power_after = next_state[0]

    temperature_after = next_state[2]

    energy_saving = (
        power_before
        - power_after
    )

    comfort_penalty = (
        occupancy
        *
        max(
            0,
            temperature_after
            - temperature_before
        )
    )

    reward = (
        energy_saving
        - comfort_penalty
    )

    return round(
        reward,
        2
    )

In [63]:
print(
    "Total States:",
    len(unique_states)
)

print(
    "Total Experiences:",
    len(experiences)
)

 


Total States: 337
Total Experiences: 1348


In [ ]:
'''experiences = []'''

In [ ]:
'''state = (
    0.9,
    0.2,
    0.7
)'''

In [ ]:
'''for action in action_space:

    next_state = get_next_state(
        state,
        action
    )

    reward = calculate_reward(
        state,
        next_state
    )

    experience = {

        "state": state,

        "action": action,

        "reward": reward,

        "next_state": next_state

    }

    experiences.append(
        experience
    )'''

In [53]:
'''for exp in experiences:

    print(exp)'''

'for exp in experiences:\n\n    print(exp)'

In [ ]:
#Create experience from all states
experiences = []

for state_id in unique_states:

    state_parts = state_id.split("-")

    current_state = (
        float(state_parts[0]),
        float(state_parts[1]),
        float(state_parts[2])
    )

    for action in action_space:

        next_state = get_next_state(
            current_state,
            action
        )

        reward = calculate_reward(
            current_state,
            next_state
        )

        experience = {

            "state": state_id,

            "action": actions[action],

            "reward": reward,

            "next_state": next_state

        }

        experiences.append(
            experience
        )

In [55]:
print(
    "Total Experiences:",
    len(experiences)
)

Total Experiences: 1348


In [56]:
#experiences of random 10 states
import random

for exp in random.sample(
    experiences,
    10
):

    print(exp)

{'state': '0.3-0.5-0.4', 'action': 'Reduce Lighting', 'reward': 0.15, 'next_state': (0.1, 0.5, 0.5)}
{'state': '0.6-0.6-0.2', 'action': 'Reduce Lighting', 'reward': 0.2, 'next_state': (0.4, 0.6, 0.2)}
{'state': '0.3-0.0-0.0', 'action': 'Do Nothing', 'reward': 0.0, 'next_state': (0.3, 0.0, 0.0)}
{'state': '0.4-0.2-0.4', 'action': 'Do Nothing', 'reward': 0.0, 'next_state': (0.4, 0.2, 0.4)}
{'state': '0.7-0.4-0.5', 'action': 'Reduce Lighting', 'reward': 0.16, 'next_state': (0.5, 0.4, 0.6)}
{'state': '0.6-0.5-0.2', 'action': 'Reduce Lighting', 'reward': 0.2, 'next_state': (0.4, 0.5, 0.2)}
{'state': '0.6-0.0-0.2', 'action': 'Do Nothing', 'reward': 0.0, 'next_state': (0.6, 0.0, 0.2)}
{'state': '1.0-0.0-0.6', 'action': 'Reduce Lighting', 'reward': 0.2, 'next_state': (0.8, 0.0, 0.7)}
{'state': '0.4-0.4-0.0', 'action': 'Reduce HVAC', 'reward': 0.26, 'next_state': (0.1, 0.4, 0.1)}
{'state': '0.1-0.1-0.5', 'action': 'Do Nothing', 'reward': 0.0, 'next_state': (0.1, 0.1, 0.5)}


In [57]:
#experience of first 10
for exp in experiences[:10]:

    print(exp)

{'state': '0.0-0.0-0.1', 'action': 'Do Nothing', 'reward': 0.0, 'next_state': (0.0, 0.0, 0.1)}
{'state': '0.0-0.0-0.1', 'action': 'Reduce HVAC', 'reward': -0.1, 'next_state': (0.1, 0.0, 0.2)}
{'state': '0.0-0.0-0.1', 'action': 'Check Equipment', 'reward': -0.1, 'next_state': (0.1, 0.0, 0.1)}
{'state': '0.0-0.0-0.1', 'action': 'Reduce Lighting', 'reward': -0.1, 'next_state': (0.1, 0.0, 0.2)}
{'state': '0.0-0.0-0.2', 'action': 'Do Nothing', 'reward': 0.0, 'next_state': (0.0, 0.0, 0.2)}
{'state': '0.0-0.0-0.2', 'action': 'Reduce HVAC', 'reward': -0.1, 'next_state': (0.1, 0.0, 0.3)}
{'state': '0.0-0.0-0.2', 'action': 'Check Equipment', 'reward': -0.1, 'next_state': (0.1, 0.0, 0.2)}
{'state': '0.0-0.0-0.2', 'action': 'Reduce Lighting', 'reward': -0.1, 'next_state': (0.1, 0.0, 0.2)}
{'state': '0.0-0.0-0.3', 'action': 'Do Nothing', 'reward': 0.0, 'next_state': (0.0, 0.0, 0.3)}
{'state': '0.0-0.0-0.3', 'action': 'Reduce HVAC', 'reward': -0.1, 'next_state': (0.1, 0.0, 0.4)}


In [58]:
experience_df = pd.DataFrame(
    experiences
)

experience_df

,state,action,reward,next_state
0,0.0-0.0-0.1,Do Nothing,0.00,"(0.0, 0.0, 0.1)"
1,0.0-0.0-0.1,Reduce HVAC,-0.10,"(0.1, 0.0, 0.2)"
2,0.0-0.0-0.1,Check Equipment,-0.10,"(0.1, 0.0, 0.1)"
3,0.0-0.0-0.1,Reduce Lighting,-0.10,"(0.1, 0.0, 0.2)"
4,0.0-0.0-0.2,Do Nothing,0.00,"(0.0, 0.0, 0.2)"
...,...,...,...,...
1343,0.9-0.1-0.4,Reduce Lighting,0.19,"(0.7, 0.1, 0.5)"
1344,1.0-0.0-0.6,Do Nothing,0.00,"(1.0, 0.0, 0.6)"
1345,1.0-0.0-0.6,Reduce HVAC,0.30,"(0.7, 0.0, 0.7)"
1346,1.0-0.0-0.6,Check Equipment,0.10,"(0.9, 0.0, 0.6)"


In [25]:
import pandas as pd

df = pd.read_excel("../data/cleandata.xlsx")

df.head()
df["Power_Norm"] = (
    df["Power Consumption"]
    - df["Power Consumption"].min()
) / (
    df["Power Consumption"].max()
    - df["Power Consumption"].min()
)

df["Occupancy_Norm"] = (
    df["Occupancy"]
    - df["Occupancy"].min()
) / (
    df["Occupancy"].max()
    - df["Occupancy"].min()
)

df["Temperature_Norm"] = (
    df["Outdoor Temperature"]
    - df["Outdoor Temperature"].min()
) / (
    df["Outdoor Temperature"].max()
    - df["Outdoor Temperature"].min()
)
df["Power_State"] = (
    (df["Power_Norm"] * 10)
    .round()
    / 10
)

df["Occupancy_State"] = (
    (df["Occupancy_Norm"] * 10)
    .round()
    / 10
)

df["Temperature_State"] = (
    (df["Temperature_Norm"] * 10)
    .round()
    / 10
)
df[[
    "Power_State",
    "Occupancy_State",
    "Temperature_State"
]].head(20)
df["State_ID"] = (
    df["Power_State"].astype(str)
    + "-"
    + df["Occupancy_State"].astype(str)
    + "-"
    + df["Temperature_State"].astype(str)
)
print(
    "Unique States:",
    df["State_ID"].nunique()
)

Unique States: 337


In [26]:
num_states = df["State_ID"].nunique()

num_actions = len(action_space)

q_table = np.zeros(
    (
        num_states,
        num_actions
    )
)

print(q_table.shape)

(337, 4)


In [27]:
q_table[:10]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
unique_states = sorted(
    df["State_ID"].unique()
)

state_to_index = {
    state: idx
    for idx, state in enumerate(unique_states)
}

index_to_state = {
    idx: state
    for state, idx in state_to_index.items()
}

print(
    list(state_to_index.items())[:10]
)

[('0.0-0.0-0.1', 0), ('0.0-0.0-0.2', 1), ('0.0-0.0-0.3', 2), ('0.0-0.0-0.4', 3), ('0.0-0.0-0.5', 4), ('0.0-0.0-0.7', 5), ('0.0-0.1-0.1', 6), ('0.0-0.1-0.2', 7), ('0.0-0.1-0.3', 8), ('0.0-0.2-0.1', 9)]


In [29]:
print("Number of States:", len(unique_states))

print("Q Table Shape:", q_table.shape)

Number of States: 337
Q Table Shape: (337, 4)


In [ ]:
#bellman equation
def update_q_value(
    state_idx,
    action,
    reward,
    next_state_idx
):

    old_value = q_table[
        state_idx,
        action
    ]

    next_max = np.max(
        q_table[
            next_state_idx
        ]
    )

    new_value = (
        old_value
        +
        alpha
        *
        (
            reward
            +
            gamma
            *
            next_max
            -
            old_value
        )
    )

    q_table[
        state_idx,
        action
    ] = new_value

In [31]:
alpha = 0.1

gamma = 0.9

episodes = 1000

In [32]:
q_table = np.zeros(
    (
        num_states,
        num_actions
    )
)

num_passes = 20

for _ in range(num_passes):

    for state in unique_states:

        state_idx = state_to_index[state]

        state_parts = state.split("-")

        current_state = (
            float(state_parts[0]),
            float(state_parts[1]),
            float(state_parts[2])
        )

        for action in action_space:

            next_state = get_next_state(
                current_state,
                action
            )

            reward = calculate_reward(
                current_state,
                next_state
            )

            next_state_id = (
                str(next_state[0])
                + "-"
                + str(next_state[1])
                + "-"
                + str(next_state[2])
            )

            if next_state_id in state_to_index:

                next_state_idx = state_to_index[
                    next_state_id
                ]

                update_q_value(
                    state_idx,
                    action,
                    reward,
                    next_state_idx
                )

In [61]:
print(
    q_table[:100]
)

[[ 0.         -0.08784233 -0.08784233 -0.08784233]
 [ 0.         -0.08784233 -0.08784233 -0.08784233]
 [ 0.         -0.08784233 -0.08784233 -0.08784233]
 [ 0.         -0.08784233 -0.08784233 -0.08784233]
 [ 0.          0.         -0.08784233  0.        ]
 [ 0.         -0.08784233  0.         -0.08784233]
 [ 0.         -0.09662657 -0.08784233 -0.09662657]
 [ 0.         -0.09662657 -0.08784233 -0.08784233]
 [ 0.         -0.09662657 -0.08784233 -0.08784233]
 [ 0.         -0.1054108  -0.08784233 -0.1054108 ]
 [ 0.          0.         -0.08784233  0.        ]
 [ 0.         -0.11419503  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.00878423  0.  

In [34]:
print("Min:", np.min(q_table))

print("Max:", np.max(q_table))

print("Mean:", np.mean(q_table))

Min: -0.114195034903226
Max: 0.49660328138173965
Mean: 0.129915262652017


In [ ]:
def get_best_action(  #given a state , what action to take
    state_id
):

    state_idx = state_to_index[
        state_id
    ]

    best_action = np.argmax(
        q_table[
            state_idx
        ]
    )

    return best_action

In [36]:
sample_state = df[ #decision cell
    "State_ID"
].iloc[0]

best_action = get_best_action(
    sample_state
)

print(
    "State:",
    sample_state
)

print(
    "Best Action:",
    actions[
        best_action
    ]
)

State: 0.4-0.0-0.4
Best Action: Reduce HVAC


In [46]:
print(
    policy_df.shape
)

(337, 2)


In [48]:
q_df = pd.DataFrame(
    q_table,
    columns=actions
)

q_df

,0,1,2,3
0,0.000000,-0.087842,-0.087842,-0.087842
1,0.000000,-0.087842,-0.087842,-0.087842
2,0.000000,-0.087842,-0.087842,-0.087842
3,0.000000,-0.087842,-0.087842,-0.087842
4,0.000000,0.000000,-0.087842,0.000000
...,...,...,...,...
332,0.266995,0.479877,0.365745,0.397616
333,0.249665,0.435050,0.321256,0.377984
334,0.210038,0.365528,0.304192,0.292381
335,0.253876,0.451325,0.342900,0.377533


In [64]:
policy_data = []

for state in unique_states:

    best_action = get_best_action(
        state
    )

    policy_data.append(
        [
            state,
            actions[best_action]
        ]
    )

policy_df = pd.DataFrame(
    policy_data,
    columns=[
        "State",
        "Best_Action"
    ]
)

print(policy_df.shape)

policy_df

(337, 2)


,State,Best_Action
0,0.0-0.0-0.1,Do Nothing
1,0.0-0.0-0.2,Do Nothing
2,0.0-0.0-0.3,Do Nothing
3,0.0-0.0-0.4,Do Nothing
4,0.0-0.0-0.5,Do Nothing
...,...,...
332,0.9-0.0-0.6,Reduce HVAC
333,0.9-0.0-0.7,Reduce HVAC
334,0.9-0.0-0.8,Reduce HVAC
335,0.9-0.1-0.4,Reduce HVAC


In [65]:
policy_df.to_csv(
    "../data/policy_table.csv",
    index=False
)